//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sepon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samples_New
    {
        public string Sample_ID { get; set; }
        public string Sample_Type { get; set; }
        public string Object_Type { get; set; }
        public Nullable<bool> Analysed { get; set; }
    }
}
