//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sepon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samples_New
    {
        public Samples_New()
        {
            this.ImagesToSample_Lookup = new HashSet<ImagesToSample_Lookup>();
            this.ResultsToSample_Lookup = new HashSet<ResultsToSample_Lookup>();
            this.Objects = new HashSet<Object>();
        }
    
        public string Sample_ID { get; set; }
        public string Sample_Type { get; set; }
        public string Object_Type { get; set; }
        public Nullable<bool> Analysed { get; set; }
    
        public virtual ICollection<ImagesToSample_Lookup> ImagesToSample_Lookup { get; set; }
        public virtual ICollection<ResultsToSample_Lookup> ResultsToSample_Lookup { get; set; }
        public virtual ICollection<Object> Objects { get; set; }
    }
}
