//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sepon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEM_ResultsDim
    {
        public string SEM_ID { get; set; }
        public string Gen_Img_ID { get; set; }
        public string SEM_Img_ID { get; set; }
        public string SEM_Type { get; set; }
        public Nullable<bool> IsBulk { get; set; }
        public Nullable<bool> IsResult { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Normalised { get; set; }
        public string Img_identifier { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
