//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sepon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeponEntities : DbContext
    {
        public SeponEntities()
            : base("name=SeponEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Image> Images { get; set; }
        public DbSet<ImageURL> ImageURLs { get; set; }
        public DbSet<Object> Objects { get; set; }
        public DbSet<Reference> References { get; set; }
        public DbSet<ResultsToSample_Lookup> ResultsToSample_Lookup { get; set; }
        public DbSet<Sample> Samples { get; set; }
        public DbSet<Samples_New> Samples_New { get; set; }
        public DbSet<SEM_Results> SEM_Results { get; set; }
        public DbSet<SEM_ResultsDim> SEM_ResultsDim { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
